apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: v1
  name: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: v1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: v1
    spec:
      initContainers:
      - name: init-index
        image: busybox
        command: ['sh', '-c', 'echo "<h1>V1 - ESTUDOS BLUE GREEN</h1>" > /usr/share/nginx/html/index.html']
        volumeMounts:
        - name: nginx-html
          mountPath: /usr/share/nginx/html
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - name: nginx-html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-html
        emptyDir: {}
